### ISSUE TITLE
Drop support for paperclip < 5.3.0

### ISSUE THREAD

**Issue by mherold** [emjot/paperclip-globalize3#16]
I'm thinking after #15 is merged we should also drop support for old paperclip versions < 5.3.0. Lower versions will have deprecation warnings in ruby 2.4+. 

(In that case, some conditional code in `attachment.rb` as well as some of the Appraisals/gemfiles could be removed.)

**Comment by McRip** [comment]
This was done with #15. Could you release a new version? Thanks in advance.

**Comment by mherold** [comment]
Please correct me if I'm wrong, but as far as I see #15 does not address this issue.

**Comment by McRip** [comment]
You're correct. I will file another MR.

**Comment by McRip** [comment]
#19

**Comment by mherold** [comment]
Done + released 4.0.0
