### ISSUE TITLE
Support globalize 5.0.x

### ISSUE THREAD

**Issue by mdkirby** [emjot/paperclip-globalize3#8]
The gem has a dependency on globalize (~> 4.0.0), will it be made to support version 5.0.x?

**Comment by mherold** [comment]
Just had a look the globalize 5.0.x changes, should just be able to loosen the dependency without any code changes - so yes, it will be made so ;-)

**Comment by mdkirby** [comment]
Awesome, FWIW, before the update was made, I cloned the repo and bumped the dependency to globalize 5.0.0 - the test suite passed, and the functionality in the application that I'm using this gem for worked - so hopefully that dependency change is all that is needed, as mentioned.
Thank you

**Comment by mherold** [comment]
Ok great, thank you for testing!
