### ISSUE TITLE
(:integer), should be :string or :text

### ISSUE THREAD

**Issue by slavajacobson** [emjot/paperclip-globalize3#9]
Following: "Migrate the paperclip columns ('xxx_file_name' etc.) of the attachment to the translation table"

   Hi, here's my migration:

```
Frame::Contribution.add_translation_fields!({exp1_photo_file_name: :string})
Frame::Contribution.add_translation_fields!({exp1_photo_content_type: :string})
Frame::Contribution.add_translation_fields!({exp1_photo_file_size: :integer})
Frame::Contribution.add_translation_fields!({exp1_photo_updated_at: :timestamp})
```

What am I missing?

**Comment by mherold** [comment]
Ah right, globalize migration helpers currently only support fields which string or text, it seems like there's some work going on to change that (see https://github.com/globalize/globalize/issues/187 and https://github.com/globalize/globalize/pull/450).

For now you could manually add the fields to the translation table (and remove them from the original table).

Hope that helps?

**Comment by bogdan8** [comment]
Please add the readme normal description of how to create a migration as transferring files, because nothing unclear

**Comment by mherold** [comment]
Hi @bogdan8,
Your question is that when you have existing attachment files, where/how to move them when you add locale support? 
The "where" depends on the change in your attachment path (what was it before, where do you insert the new ':locale' interpolation part). The "how" could be, for instance, like described in https://github.com/thoughtbot/paperclip/wiki/Changing-attachment-:path

**Comment by mherold** [comment]
Closing because stale.
